[package]
name = "printf-helper"
version = "0.1.0"
authors = [
    "Richard Dodd <richard.o.dodd@gmail.com>",
    "James Zhu <jameszhu@berkeley.edu>",
]
build = "build.rs"

[dependencies]
libc = "^0.2"

[build-dependencies]
cc = "^1.0"
